name: publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          name: Install Python
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine build

        - name: Build source and wheel distributions
          run: |
            python -m build --sdist --wheel

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: dist

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]

    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          # user: __token__
          # password: ${{ secrets.PYPI_PASSWORD }}
          # To test, uncomment the following:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository-url: https://test.pypi.org/legacy/
